/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HajimeAPI4J.api;

public abstract class HajimeAPI4J {

    public static final String DATE_FORMAT_STRING = "yyyy-MM-dd";
    public static final String BASE_URI = "https://api.fujiwarahaji.me/v1/";

}
