/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HajimeAPI4J;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    
}
