
name: Java Test with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradle wrapper
      run: chmod +x gradlew
    - name: Tests with Gradle
      run: ./gradlew test --refresh-dependencies --no-build-cache --no-daemon